### ISSUE TITLE
Programmatically getting notion to render the HTML/Markdown

### ISSUE THREAD

**Issue by shrik450** [Mathspy/notion-generator#1]
Hey! Please disregard this if you already know, but just in case: you *can* get Notion to give you Markdown or HTML for a notion page by using the endpoints the webapp talks to. It's a fairly involved process and needs three requests for each page:

```sh
curl 'https://www.notion.so/api/v3/enqueueTask' -X POST -H 'Content-Type: application/json' -H 'Cookie: token_v2={{secret}};' --data-raw '{"task":{"eventName":"exportBlock","request":{"block":{"id":"{{id}}"},"recursive":false,"exportOptions":{"exportType":"html","timeZone":"Asia/Kolkata","locale":"en"}}}}'
#=> task id

curl 'https://www.notion.so/api/v3/getTasks' -X POST -H 'Content-Type: application/json' -H 'Cookie: token_v2={{secret}};' --data-raw '{"taskIds":["{{task id}}"]}'
# => s3 url

# curl/wget the s3 url
```

The output HTML is pretty much as it looks on notion minus the JS. Of course, this isn't supposed to be their "official" API, and they might deprecate it or lock it down any moment.

**Comment by Mathspy** [comment]
Hey thank you very much! ❤️ I did know about the unofficial API but not this particular endpoint
And yeah I intentionally avoided this API since I wanted to use the official API to be on the safe side, even if they don’t deprecate it that’s their internal API and they can change it any day to update their apps and I would really like not to deal with that. 
This also gives more freedom in how things can be generated and also styled (I intend to use this for a blog that I want to manage from a Notion document but I don’t want it to have default Notion styles)

**Comment by shrik450** [comment]
That's fair, and I completely agree! I was also interested in generating statically rendered pages from notion, but I eventually gave up because it was tedious to do + getting a reliable "push" from notion when a page was updated required a server polling all the time. In hindsight, a system like this with a manual build would've been better.

**Comment by Mathspy** [comment]
I intend to use a cronjob CloudFlare Worker to do the polling, I’ll be open sourcing that as well in few days (once I actually write it…) and I can post it here if you’re interested! Should be possible to run it on their free Workers plan
